#!/usr/bin/env python3
"""Builds apps-script/SeedData.gs from the CSV exports in source/.

Run from the wellbeing-training folder:  python3 tools/build-seed.py
The seed is only used by setup() the first time, to fill an empty Sheet.
"""
import csv, json, re, collections, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "source"

def read(name):
    with open(src / name, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))

overview = [r for r in read("Training_Overview.csv") if re.match(r"^\d+\.", r["Training Topic"])]
plan = {r["Training Topic"].split(".")[0]: r for r in read("Detailed_Training_Plan.csv") if re.match(r"^\d+\.", r["Training Topic"])}
tracker = read("10_Cycle_Master_Tracker.csv")

topics = []
for r in overview:
    num, name = r["Training Topic"].split(". ", 1)
    p = plan[num]
    notes = []
    if p["SM's Comments"].strip():
        notes.append("SM: " + p["SM's Comments"].strip())
    if p["Discussion Points"].strip():
        notes.append("To discuss:\n" + p["Discussion Points"].strip())
    topics.append({"id": int(num), "name": name, "weight": float(r["Weightage"].rstrip("%")), "note": "\n\n".join(notes)})

# The tracker lost two task numbers when Sheets read "5.10" and "10.10" as decimals.
FIX = {("5.1", "Role Play - 'I Don't Know' Student"): "5.10",
       ("10.1", "Principal Readiness Sign-off"): "10.10"}
dups = [k for k, v in collections.Counter(r["Task ID"] for r in tracker).items() if v > 1]
assert sorted(dups) == ["10.1", "5.1"], dups

tasks = []
for i, r in enumerate(tracker, 1):
    tid = FIX.get((r["Task ID"], r["Task / Activity"]), r["Task ID"])
    tasks.append({
        "id": tid, "topic": int(r["Training Topic"].split(".")[0]), "cycle": int(r["Cycle"].lstrip("C")),
        "name": r["Task / Activity"], "type": r["Task Type"], "what": r["What the New Joinee Will Do"],
        "evidence": r["Evidence / Output"], "standard": r["Competency Standard"],
        "weight": float(r["Task Weight %"]), "gate": r["Critical Gate?"] == "TRUE",
        "mandatory": r["Mandatory Before Independent Cases?"] == "Yes", "active": True, "order": i,
    })
assert len({t["id"] for t in tasks}) == len(tasks)

phases = []
by_phase = collections.OrderedDict()
for r in tracker:
    by_phase.setdefault(r["Phase"], []).append(int(r["Cycle"].lstrip("C")))
for name, cycles in by_phase.items():
    phases.append({"name": name, "from": min(cycles), "to": max(cycles)})

resources = []
for num, p in plan.items():
    for label in [x.strip() for x in p["Input / Resource"].split(";") if x.strip()]:
        resources.append({"topic": int(num), "task": "", "label": label, "url": "", "note": ""})
resources.append({"topic": 5, "task": "5.12", "label": "Trauma-Informed Intervention certification (Connect & Restore)",
                  "url": "https://connectandrestore.in/trauma-informed-training",
                  "note": "Online, 7 days, 6pm to 9pm (3 hours a day). Rs 7,000-8,000. Fee to be borne by the school if possible."})

seed = {
    "settings": {"cycles": 10, "daysPerCycle": 6, "passScore": 3, "supervisedGateCycle": 5, "urgentGateCycle": 2, "maxUploadMb": 10},
    "phases": phases, "topics": topics, "tasks": tasks, "resources": resources,
}
def compact(seed):
    """One line per record keeps the file short enough to paste in one go and still easy to read."""
    lines = []
    for key, value in seed.items():
        if isinstance(value, list):
            body = ",\n".join("  " + json.dumps(v, ensure_ascii=False) for v in value)
            lines.append(" %s: [\n%s\n ]" % (json.dumps(key), body))
        else:
            lines.append(" %s: %s" % (json.dumps(key), json.dumps(value, ensure_ascii=False)))
    return "{\n" + ",\n".join(lines) + "\n}"

out = root / "apps-script" / "SeedData.gs"
out.write_text("// Generated by tools/build-seed.py from source/*.csv. Do not edit by hand.\nconst SEED = "
               + compact(seed) + ";\n", encoding="utf-8")
print("topics", len(topics), "tasks", len(tasks), "resources", len(resources), "phases", phases)
